[build]
  command = "cd platform/app && yarn install && yarn build:viewer:ci"
  publish = "platform/app/dist"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"