[build]
  base = "platform/app"
  command = "yarn install && yarn run build:netlify"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NODE_OPTIONS = "--max_old_space_size=4096"