[build]
  base = "platform/app"
  command = "yarn install && yarn build:viewer:ci"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"